### ISSUE TITLE
About license

### ISSUE THREAD

**Issue by fmiguelgarcia** [francoiscolas/libqmhd#2]
Hi Françoi,
I cannot find the license. 
I would like to use this lib, but I am looking for LGPL or MIT license.

**Comment by InScene** [comment]
Hi @francoiscolas,
is it okay if we take your code for our project? Is the code freely available to everyone or do you have a special license or terms of use in mind?

Best regards,
Christian

**Comment by francoiscolas** [comment]
GPL, I will update the repo soon.
